### ISSUE TITLE
[MoreItemsLibrary] Broken hook (PlayFabMirror.get_all_inventory_items); prevents creating items

### ISSUE THREAD

**Issue by Zeropathic** [Aussiemon/Vermintide-2-JHF-Mods#4]
This mod broke after the Season 3 update.

This error is posted in chat upon game launch:
`[MOD][MoreItemsLibrary][ERROR] (hook): argument 'obj' should have the 'string/table' type, not 'nil'`

The function the mod tries to hook is `PlayFabMirror.get_all_inventory_items`

From my cursory testing (no game source code yet), it appears `PlayFabMirror` has either been renamed or deleted, so the hook fails.

**Comment by Aussiemon** [comment]
https://github.com/Aussiemon/VT2-More-Items-Library/commit/2a35a2712b4a70bed3b19a64c7442b5d2f7bc5bd

Added your fix and seems to resolve the error. Haven't had a chance to do any in-depth testing though.
